### ISSUE TITLE
Form dropdown background is white, when it should be transparent

### ISSUE THREAD

**Issue by derekstavis** [pagarme/former-kit-skin-pagarme#129]
In Safari I'm getting this:

<img width="1275" alt="screen shot 2018-08-27 at 12 20 19" src="https://user-images.githubusercontent.com/1611639/44684203-51dc1d00-a9fd-11e8-8367-c1e090c16ee1.png">

Probably it was supposed to be transparent but there is something which has white background.

**Comment by lucasjs** [comment]
@derekstavis already done. https://github.com/pagarme/former-kit-skin-pagarme/pull/126
