### ISSUE TITLE
Tooltip doesn't appear on expanded Sidebar

### ISSUE THREAD

**Issue by miglsoares** [pagarme/former-kit-skin-pagarme#168]
### Context
After Microinteration's Sidebar merge, the tooltip with Anticipation and Balance doesn't appear on expanded Sidebar. It seems like a fake button to the user.
To make the screenshot gif, I had to put the property `left: 20;`. Something is pushing the tooltip too much to the left.

### Screenshots
![tooltip](https://user-images.githubusercontent.com/20358128/54929167-eb1bd500-4ef3-11e9-81e3-51ce18decc3b.gif)

### Technical Description
We need to investigate more.

### Requirements
- [ ] Tooltip working property on expanded Sidebar

**Comment by rsmelo** [comment]
já foi resolvido
