### ISSUE TITLE
Alterar fonte para Rubik

### ISSUE THREAD

**Issue by rsmelo** [pagarme/former-kit-skin-pagarme#185]
Currently, the font used has some problems such as lack of accentuation and special characters.
It was defined with the UX team the need to update the source to [Rubik font](https://fonts.google.com/selection?selection.family=Rubik:300,400,500,700)

### Requirements
- [ ] Change the font in the typography configuration.
~Add the new color `#4d4f62` (we need a new name ?)~
- [ ] Fix the components which are affected by font weight and size. The following list will be used to document the affected components:

#### Table
- [ ] Change the header `font-weight` to `normal`.
- [ ] Change the header font `color` to `color-grey-100`.

#### CardTitle
- [ ] Add prop to allow not upper case text.
- [ ] Change the font color to `color-coal-100`.

#### Button
- [ ] Change the `font-weight` to `normal`.

#### Input
- [ ] Change the default `font-size` to `12px`.
- [ ] Add style fix to avoid the browsers default background and color when the browser’s auto-complete is set over the input.

### Related issues
https://github.com/pagarme/pilot/issues/1306

**Comment by Deivis** [comment]
Testamos a troca da fonte mas acabamos vendo que não ficou muito bom, dado isso a @alexandralugli  irá revisar as aplicaaplicações da fonte `Rubik` nas telas e com base nestas alterações  vamos gerar mais issues para fazemos estes ajustes na pilot e no former-kit. Por hora temos uma [branch no former-kit-skin-pagarme](https://github.com/pagarme/former-kit-skin-pagarme/tree/update/font-family) que está fazendo a troca da fonte apenas, os demais ajustes necessários iremos fazer depois da análise de design.

**Comment by alexandralugli** [comment]
Estou subindo as telas nessa seção do Zeplin: https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5d387e2ab0bb176314e09d1e

**Comment by alexandralugli** [comment]
Extrato: https://zpl.io/aNzKvNN

![Extrato - a receber - versao inicial - troca de fontes](https://user-images.githubusercontent.com/8549244/61809657-2253b180-ae14-11e9-9644-78253d941323.jpg)

**Comment by alexandralugli** [comment]
Lista de transações: https://zpl.io/anLdZJr

![Transações_lista - troca de fontes@2x](https://user-images.githubusercontent.com/8549244/61823679-9bfa9800-ae32-11e9-8368-09f877d8d212.jpg)

**Comment by alexandralugli** [comment]
Transações grafico

![image](https://user-images.githubusercontent.com/8549244/61966717-b60ab680-afa9-11e9-9ad2-7a2f8b5695ce.png)


Saque
![image](https://user-images.githubusercontent.com/8549244/61966793-f36f4400-afa9-11e9-98e5-63ae4ab95529.png)
![image](https://user-images.githubusercontent.com/8549244/61966808-fc601580-afa9-11e9-8464-ea9ae87c4daf.png)

**Comment by alexandralugli** [comment]
Detalhes da transação

![image](https://user-images.githubusercontent.com/8549244/61972917-21a85000-afb9-11e9-87e5-a416eaf5d62e.png)

**Comment by alexandralugli** [comment]
![image](https://user-images.githubusercontent.com/8549244/61981037-dc8f1880-afce-11e9-88d2-6291121d53ce.png)
