### ISSUE TITLE
Legend: font-size e color do text estão diferentes do zeplin

### ISSUE THREAD

**Issue by rsmelo** [pagarme/former-kit-skin-pagarme#73]
## Contexto
hoje no zeplin os valores para as propriedades no css do `.text` da `Legend` estão:
`font-size: 11px`
`color: #757575`

atualmente está sendo utilizado:
`font-size: 10px`
`color: #a0a0a0`

![screenshot from 2018-05-17 14-04-52](https://user-images.githubusercontent.com/479495/40192638-59f630b0-59db-11e8-98fa-3d4a396be88e.png)

### Descrição técnica
- [x] atualizar os estilos da `Legend` conforme definido no zeplin

**Comment by lucasjs** [comment]
https://github.com/pagarme/former-kit-skin-pagarme/pull/75
